FROM ghcr.io/make87/python3-dev:latest

## Custom Add-ons

RUN apt-get update \
    && apt-get install --no-install-suggests --no-install-recommends -y \
        ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*